### ISSUE TITLE
[SEMI-CRITICAL] Using Discord to verify people is a bad idea

### ISSUE THREAD

**Issue by spudpiggy** [Myuui/Free-Minecraft-Hosts#9]
adding someone to verify is a very bad idea.

1. If the verifier is away, you can't verify
2. due to timezones, some users have to talk to the verifier asynchronously, so could take days to get verified
3. If something happens to the verifier, you can't verify at all
4. If Discord is down, you can't verify at all
5. It's way too much effort to verify

please verify in another way, it's what put me off the form completely.
if you can, use a recaptcha or something

**Comment by Myuui** [comment]
that's why I made a forms at the top

**Comment by Myuui** [comment]
If you know a better alternative, I'll take it!

**Comment by SudoVanilla** [comment]
I keep telling people this, but companies don't listen >:C
I even ranted on Drama.gg mentioning about Discord being the "only auth method".
https://drama.gg/d/2117-im-sick-of-hositng-companies-and-this-needs-to-be-taken-care-of
